language: objective-c
before_install:
  - brew update
  - brew unlink xctool
  - brew install xctool
  - rvm get stable
  - rvm install 2.1.0
  - rvm use 2.1.0
script: rake test
cache:
  bundler: true
  directories:
  - Pods
notifications:
  email: false
